# Generated by Django 4.1.4 on 2022-12-20 01:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_pupil_fullname_pupil_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('amount', models.IntegerField(verbose_name="To'lov")),
                ('note', models.TextField(verbose_name="Eslatma / To'lov tarifi")),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('updated', models.DateField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('pupil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.pupil')),
            ],
        ),
    ]
