# Generated by Django 4.1.4 on 2022-12-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name="To'lov vaqti"),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated',
            field=models.DateField(auto_now=True, null=True, verbose_name="O'zgartirilgan vaqt"),
        ),
    ]
