# Generated by Django 4.1.4 on 2022-12-21 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_payment_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='fullname',
            field=models.CharField(max_length=200, null=True, verbose_name="To'liq Ism va Familiya"),
        ),
    ]
