# Generated by Django 4.1.4 on 2022-12-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_group_created_alter_group_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Ism'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Familiya'),
        ),
    ]
