# Generated by Django 4.1.4 on 2022-12-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='fullname',
            field=models.CharField(max_length=200, verbose_name="To'liq Ism Familiya"),
        ),
    ]
